from __future__ import annotations

import argparse
import json
import pickle
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


def _short_checkpoint(path: str) -> str:
    name = Path(path).name
    return name or path


def _row_action_count(row: Any) -> int:
    mask = getattr(row, "launch_mask", None)
    if mask is None:
        return int(getattr(row, "dagger_regular_label_action_count", 0))
    return int(mask.sum())


def _bucket_turn(turn: int, width: int) -> str:
    if turn < 0:
        return "unknown"
    lo = (turn // width) * width
    return f"{lo:03d}-{lo + width - 1:03d}"


def summarize(rows: list[Any], turn_bucket: int) -> dict[str, Any]:
    by_checkpoint: Counter[str] = Counter()
    by_turn: Counter[str] = Counter()
    by_reward: Counter[str] = Counter()
    action_gap_by_turn: dict[str, list[float]] = defaultdict(list)
    action_gap_by_reward: dict[str, list[float]] = defaultdict(list)
    label_actions = 0
    model_actions = 0
    missing_turn = 0
    missing_final = 0

    for row in rows:
        checkpoint = _short_checkpoint(str(getattr(row, "dagger_checkpoint", "unknown")))
        turn = int(getattr(row, "dagger_turn_index", getattr(row, "dagger_obs_step", -1)))
        if turn < 0:
            missing_turn += 1
        reward_value = getattr(row, "dagger_model_final_reward", None)
        if reward_value is None:
            reward_key = "unknown"
            missing_final += 1
        else:
            reward = float(reward_value)
            reward_key = "win" if reward > 0 else "loss" if reward < 0 else "draw"

        label_count = int(getattr(row, "dagger_regular_label_action_count", _row_action_count(row)))
        model_count = int(getattr(row, "dagger_model_action_count", 0))
        gap = float(label_count - model_count)
        turn_key = _bucket_turn(turn, turn_bucket)

        by_checkpoint[checkpoint] += 1
        by_turn[turn_key] += 1
        by_reward[reward_key] += 1
        action_gap_by_turn[turn_key].append(gap)
        action_gap_by_reward[reward_key].append(gap)
        label_actions += label_count
        model_actions += model_count

    def gap_summary(values: list[float]) -> dict[str, float]:
        if not values:
            return {"mean": 0.0, "abs_mean": 0.0, "count": 0.0}
        return {
            "mean": sum(values) / len(values),
            "abs_mean": sum(abs(value) for value in values) / len(values),
            "count": float(len(values)),
        }

    return {
        "rows": len(rows),
        "label_actions": label_actions,
        "model_actions": model_actions,
        "mean_label_actions_per_row": label_actions / max(1, len(rows)),
        "mean_model_actions_per_row": model_actions / max(1, len(rows)),
        "missing_turn": missing_turn,
        "missing_final": missing_final,
        "by_checkpoint": dict(by_checkpoint.most_common()),
        "by_turn": dict(sorted(by_turn.items())),
        "by_reward": dict(by_reward.most_common()),
        "action_gap_by_turn": {key: gap_summary(values) for key, values in sorted(action_gap_by_turn.items())},
        "action_gap_by_reward": {key: gap_summary(values) for key, values in sorted(action_gap_by_reward.items())},
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("cache", help="DAgger pickle cache generated by imitation_regular_ray.py")
    parser.add_argument("--turn-bucket", type=int, default=50)
    parser.add_argument("--out", default="", help="Optional JSON output path.")
    args = parser.parse_args()

    with Path(args.cache).open("rb") as fh:
        payload = pickle.load(fh)
    rows = list(payload.get("rows", []))
    summary = {
        "cache": args.cache,
        "cache_metrics": payload.get("metrics", {}),
        "summary": summarize(rows, max(1, int(args.turn_bucket))),
    }
    text = json.dumps(summary, ensure_ascii=True, indent=2)
    if args.out:
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.out).write_text(text + "\n")
    print(text)


if __name__ == "__main__":
    main()
